const Recipe = [
    {
        id: 1,
        image: "images/t.jpg",
        name: "Tteokbokki",
        des: "Tteokbokki is a highly popular Korean street food and a delicious comfort food. You can make it at home with this easy tteokbokki recipe. The spicy, slightly sweet, and chewy rice cakes are simply addictive!",
        time: "35 mins",
        ingrdnt: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaque",
        rcp: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaque",
        vdl: "Watch",
        type: "Veg"
    },

    {
        id: 2,
        image: "images/ct.jpg",
        name: "Chicken Teriyaki",
        des: "This American-style chicken teriyaki is a little salty, a little sweet, a little sour, and has just the tiniest hint of spice from minced ginger. Serve it up with a side of steamed rice and broccoli ",
        time: "40 mins",
        ingrdnt: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaque",
        rcp: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaque",
        vdl: "Watch",
        type: "Non-Veg"
    },

    {
        id: 3,
        image: "images/bj.jpg",
        name: "Budae Jjigae (Army Stew)",
        des: "The best and the most popular Korean hot pot dish - Budae Jjigae (Army stew / Army base stew) recipe! It is loaded with Kimchi, spam, sausages, ramen noodles and much more!",
        time: "30 mins",
        ingrdnt: " 4 cups chicken stock (1 litre), 200 g SPAM thinly sliced, 4 cocktail Frankfurt sausages (150g) thinly & diagonally sliced",
        rcp: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaque",
        vdl: "Watch",
        type: "Veg"
    },

    {
        id: 4,
        image: "images/sbwbs.jpg",
        name: "Sushi Bowl with Baked Salmon",
        des: "These deconstructed sushi definitely have key ingredients that makes up the sushi we all know and love, just without the intensely fine slicing of vegetables and the difficult (even though artistic and beautiful) rolling of the sushi.",
        time: "30 mins",
        ingrdnt: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaque",
        rcp: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaque",
        vdl: "Watch",
        type: "Non-Veg"
    },

    {
        id: 5,
        image: "images/sckn.jpg",
        name: "Spicy Cold Kimchi Noodles",
        des: "There's no better way to beat the hot summer weather than having some addictively spicy Korean noodles! As you can imagine from the title, it's loaded with kimchi!",
        time: "20 mins",
        ingrdnt: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaque",
        rcp: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaque",
        vdl: "Watch",
        type: "Veg"
    },

    {
        id: 6,
        image: "images/vnb.jpg",
        name: "Vietnamese Rice Noodle Bowl",
        des: "Vermicelli noodles topped with chargrilled pork, crunchy veggies, lime and peanuts. A healthy and light meal bursting with freshness and packed with so much yum! Vietnamese Noodle Bowl is the epitome of great flavor and texture.",
        time: "40 mins",
        ingrdnt: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaque",
        rcp: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaque",
        vdl: "Watch",
        type: "Non-Veg"
    },

    {
        id: 7,
        image: "images/vcsr.jpg",
        name: "Vegan Char Siu Bao",
        des: "This vegan Char Siu (BBQ Tofu) Rice or 素叉烧饭 (Sù Chā shāo fàn) is a must-try dish! It has a drool-worthy BBQ Tofu made with homemade sauce and paired with fragrant ginger garlic rice.",
        time: "30 mins",
        ingrdnt: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaque",
        rcp: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaque",
        vdl: "Watch",
        type: "Vegan"
    },

    {
        id: 8,
        image: "images/jfp.jpg",
        name: "Japanese Souffle Pancakes",
        des: "A Japanese soufflé pancake is a pancake made using soufflé techniques. Soufflé pancakes are fluffy, jiggly, sweet, soft, and so, so delicious. They taste like you are eating a sweet pancake cloud, with butter and syrup!",
        time: "30 mins",
        ingrdnt: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaque",
        rcp: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaqueLorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum fugit, at saepe, quaerat eligendi eveniet expedita in porro quibusdam voluptatem earum ea consequuntur ducimus itaque",
        vdl: "Watch",
        type: "Vegan"
    },
        

];

export default Recipe;

